# Generated by Django 3.0.7 on 2020-07-17 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200716_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image6',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
    ]
