# Generated by Django 3.0.7 on 2020-07-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
    ]
